# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from My_App import MemoApp

memoApp = MemoApp.Memo_App()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(531, 304)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 511, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.friend_name_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.friend_name_label.setObjectName("friend_name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.friend_name_label)
        self.friend_name_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.friend_name_line.setObjectName("friend_name_line")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.friend_name_line)
        self.horizontalLayout.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.birthday_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.birthday_label.setObjectName("birthday_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.birthday_label)
        self.birthday_date = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.birthday_date.setObjectName("birthday_date")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.birthday_date)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.birthday_add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.birthday_add.setObjectName("birthday_add")
        self.horizontalLayout.addWidget(self.birthday_add)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.delete_friend = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.delete_friend.setObjectName("delete_friend")
        self.horizontalLayout_2.addWidget(self.delete_friend)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.friends_list = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.friends_list.setObjectName("friends_list")
        self.horizontalLayout_2.addWidget(self.friends_list)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidget.setRowCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.tableWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 531, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.birthday_add.clicked.connect(self.add_friend)
        self.delete_friend.clicked.connect(self.delete_friend_1)
        self.pushButton.clicked.connect(self.birthday_reminder)
        self.friends_list.clicked.connect(self.refilling_table)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.friend_name_label.setText(_translate("MainWindow", "Имя друга"))
        self.birthday_label.setText(_translate("MainWindow", "Дата рождения"))
        self.birthday_add.setText(_translate("MainWindow", "Добавить друга"))
        self.delete_friend.setText(_translate("MainWindow", "Удалить друга"))
        self.pushButton.setText(_translate("MainWindow", "Напоминанаие"))
        self.friends_list.setText(_translate("MainWindow", "Список друзей"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Дата рождения"))

    def delete_friend_1(self):
        selected_item = self.tableWidget.selectedItems()
        if len(selected_item) == 0:  # если строка не выбрана
            return
        else:
            memoApp.delete_friend_birthday(selected_item[0].text(), selected_item[1].text())
            memoApp.filling_table(self.tableWidget)

    def add_friend(self):
        frien_name = self.friend_name_line.text()
        birthday = self.birthday_date.text()
        memoApp.add_friend_birthday(frien_name, birthday)
        memoApp.filling_table(self.tableWidget)

    def birthday_reminder(self):
        flag, friend_list = memoApp.birthday_reminder()
        if flag:
            memoApp.filling_table_1(self.tableWidget, friend_list)

    def refilling_table(self):
        memoApp.filling_table(self.tableWidget)